version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_LINK=$DB_LINK
      - DB_DATABASE=$DB_DATABASE
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    command: ["npm", "start"]